[tool.poetry]
name = "python-api"
version = "0.1.0"
description = ""
authors = ["Daniss <jonni-33-33@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
